package com.yunfatong.evidence.mapper;

import com.yunfatong.evidence.model.RegionAmap;
import com.yunfatong.evidence.model.RegionAmapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegionAmapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    int countByExample(RegionAmapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    int deleteByExample(RegionAmapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    int insert(RegionAmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    int insertSelective(RegionAmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    List<RegionAmap> selectByExample(RegionAmapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    RegionAmap selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") RegionAmap record, @Param("example") RegionAmapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    int updateByExample(@Param("record") RegionAmap record, @Param("example") RegionAmapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    int updateByPrimaryKeySelective(RegionAmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    int updateByPrimaryKey(RegionAmap record);
}