package com.yunfatong.evidence.mapper;

import com.yunfatong.evidence.model.RegionOrder;
import com.yunfatong.evidence.model.RegionOrderExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RegionOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_order
     *
     * @mbggenerated Wed Jan 30 13:02:44 CST 2019
     */
    int countByExample(RegionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_order
     *
     * @mbggenerated Wed Jan 30 13:02:44 CST 2019
     */
    int deleteByExample(RegionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_order
     *
     * @mbggenerated Wed Jan 30 13:02:44 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_order
     *
     * @mbggenerated Wed Jan 30 13:02:44 CST 2019
     */
    int insert(RegionOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_order
     *
     * @mbggenerated Wed Jan 30 13:02:44 CST 2019
     */
    int insertSelective(RegionOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_order
     *
     * @mbggenerated Wed Jan 30 13:02:44 CST 2019
     */
    List<RegionOrder> selectByExample(RegionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_order
     *
     * @mbggenerated Wed Jan 30 13:02:44 CST 2019
     */
    RegionOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_order
     *
     * @mbggenerated Wed Jan 30 13:02:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") RegionOrder record, @Param("example") RegionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_order
     *
     * @mbggenerated Wed Jan 30 13:02:44 CST 2019
     */
    int updateByExample(@Param("record") RegionOrder record, @Param("example") RegionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_order
     *
     * @mbggenerated Wed Jan 30 13:02:44 CST 2019
     */
    int updateByPrimaryKeySelective(RegionOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_order
     *
     * @mbggenerated Wed Jan 30 13:02:44 CST 2019
     */
    int updateByPrimaryKey(RegionOrder record);
}