package com.yunfatong.evidence.model;

import java.io.Serializable;

public class RegionAmap implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_amap.id
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_amap.adcode
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private String adcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_amap.citycode
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private Integer citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_amap.center
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private String center;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_amap.level
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_amap.merger_name
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private String mergerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_amap.name
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_amap.parent_id
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_amap.pinyin
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_amap.short_name
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_amap.zip_code
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table region_amap
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_amap.id
     *
     * @return the value of region_amap.id
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_amap.id
     *
     * @param id the value for region_amap.id
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_amap.adcode
     *
     * @return the value of region_amap.adcode
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public String getAdcode() {
        return adcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_amap.adcode
     *
     * @param adcode the value for region_amap.adcode
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public void setAdcode(String adcode) {
        this.adcode = adcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_amap.citycode
     *
     * @return the value of region_amap.citycode
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public Integer getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_amap.citycode
     *
     * @param citycode the value for region_amap.citycode
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public void setCitycode(Integer citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_amap.center
     *
     * @return the value of region_amap.center
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public String getCenter() {
        return center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_amap.center
     *
     * @param center the value for region_amap.center
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public void setCenter(String center) {
        this.center = center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_amap.level
     *
     * @return the value of region_amap.level
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_amap.level
     *
     * @param level the value for region_amap.level
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_amap.merger_name
     *
     * @return the value of region_amap.merger_name
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public String getMergerName() {
        return mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_amap.merger_name
     *
     * @param mergerName the value for region_amap.merger_name
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public void setMergerName(String mergerName) {
        this.mergerName = mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_amap.name
     *
     * @return the value of region_amap.name
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_amap.name
     *
     * @param name the value for region_amap.name
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_amap.parent_id
     *
     * @return the value of region_amap.parent_id
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_amap.parent_id
     *
     * @param parentId the value for region_amap.parent_id
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_amap.pinyin
     *
     * @return the value of region_amap.pinyin
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_amap.pinyin
     *
     * @param pinyin the value for region_amap.pinyin
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_amap.short_name
     *
     * @return the value of region_amap.short_name
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_amap.short_name
     *
     * @param shortName the value for region_amap.short_name
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_amap.zip_code
     *
     * @return the value of region_amap.zip_code
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_amap.zip_code
     *
     * @param zipCode the value for region_amap.zip_code
     *
     * @mbggenerated Wed Jan 30 13:03:56 CST 2019
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
}